"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var category_1 = require("./category");
var users_1 = require("./users");
var courses_1 = require("./courses");
var topics_1 = require("./topics");
var tags_1 = require("./tags");
var usersObj = (0, users_1.default)();
var tagsObj = (0, tags_1.default)();
var categoriesObj = (0, category_1.default)();
var topicsObj = (0, topics_1.default)(categoriesObj.sub_categories);
(0, courses_1.default)(categoriesObj.categories, usersObj.users, usersObj.creators, tagsObj.tagsIds, topicsObj.map_category_topics);
