insert into public.category (id, name) values(1, 'Devlopment');
insert into public.category (id, name) values(2, 'Business');
insert into public.category (id, name) values(3, 'Finance & Accounting');
insert into public.category (id, name) values(4, 'IT & Software');
insert into public.category (id, name) values(5, 'Office Productivity');
insert into public.category (id, name) values(6, 'Personal Devlopment');
insert into public.category (id, name) values(7, 'Design');
insert into public.category (id, name) values(8, 'Marketing');
insert into public.category (id, name) values(9, 'Lifestyle');
insert into public.category (id, name) values(10, 'Photography & Video');
insert into public.category (id, name) values(11, 'Health & Fitness');
insert into public.category (id, name) values(12, 'Music');
insert into public.category (id, name) values(13, 'Teaching & Academics');
insert into public.sub_category (id, name, category_id) values(1, 'Web Devlopment', 1);
insert into public.sub_category (id, name, category_id) values(2, 'Data Science', 1);
insert into public.sub_category (id, name, category_id) values(3, 'Mobile Devlopment', 1);
insert into public.sub_category (id, name, category_id) values(4, 'Programming Languages', 1);
insert into public.sub_category (id, name, category_id) values(5, 'Game Development', 1);
insert into public.sub_category (id, name, category_id) values(6, 'Database Design & Devlopment', 1);
insert into public.sub_category (id, name, category_id) values(7, 'Software Testing', 1);
insert into public.sub_category (id, name, category_id) values(8, 'Software Engineering', 1);
insert into public.sub_category (id, name, category_id) values(9, 'Software Development Tools', 1);
insert into public.sub_category (id, name, category_id) values(10, 'No-Code Devlopment', 1);
insert into public.sub_category (id, name, category_id) values(11, 'Entrepreneurship', 2);
insert into public.sub_category (id, name, category_id) values(12, 'Communication', 2);
insert into public.sub_category (id, name, category_id) values(13, 'Management', 2);
insert into public.sub_category (id, name, category_id) values(14, 'Sales', 2);
insert into public.sub_category (id, name, category_id) values(15, 'Business Strategy', 2);
insert into public.sub_category (id, name, category_id) values(16, 'Operations', 2);
insert into public.sub_category (id, name, category_id) values(17, 'Project Management', 2);
insert into public.sub_category (id, name, category_id) values(18, 'Business Law', 2);
insert into public.sub_category (id, name, category_id) values(19, 'Business Analytics & Intelligence', 2);
insert into public.sub_category (id, name, category_id) values(20, 'Human Resources', 2);
insert into public.sub_category (id, name, category_id) values(21, 'Industry', 2);
insert into public.sub_category (id, name, category_id) values(22, 'E-Commerce', 2);
insert into public.sub_category (id, name, category_id) values(23, 'Media', 2);
insert into public.sub_category (id, name, category_id) values(24, 'Real Estate', 2);
insert into public.sub_category (id, name, category_id) values(25, 'Other Business', 2);
insert into public.sub_category (id, name, category_id) values(26, 'Accounting & Blockchain', 3);
insert into public.sub_category (id, name, category_id) values(27, 'Compliance', 3);
insert into public.sub_category (id, name, category_id) values(28, 'Cryptocurrency & Blockchain', 3);
insert into public.sub_category (id, name, category_id) values(29, 'Economics', 3);
insert into public.sub_category (id, name, category_id) values(30, 'Finance', 3);
insert into public.sub_category (id, name, category_id) values(31, 'Finance Cert & Exam Prep', 3);
insert into public.sub_category (id, name, category_id) values(32, 'Financial Modeling & Analysis', 3);
insert into public.sub_category (id, name, category_id) values(33, 'Investing & Trading', 3);
insert into public.sub_category (id, name, category_id) values(34, 'Money Management Tools', 3);
insert into public.sub_category (id, name, category_id) values(35, 'Taxes', 3);
insert into public.sub_category (id, name, category_id) values(36, 'Other Finance & Accounting', 3);
insert into public.sub_category (id, name, category_id) values(37, 'IT Certifications', 4);
insert into public.sub_category (id, name, category_id) values(38, 'Network & Security', 4);
insert into public.sub_category (id, name, category_id) values(39, 'Hardware', 4);
insert into public.sub_category (id, name, category_id) values(40, 'Operating Systems & Servers', 4);
insert into public.sub_category (id, name, category_id) values(41, 'Other IT & Software', 4);
insert into public.sub_category (id, name, category_id) values(42, 'Microsoft', 5);
insert into public.sub_category (id, name, category_id) values(43, 'Apple', 5);
insert into public.sub_category (id, name, category_id) values(44, 'Google', 5);
insert into public.sub_category (id, name, category_id) values(45, 'SAP', 5);
insert into public.sub_category (id, name, category_id) values(46, 'Oracle', 5);
insert into public.sub_category (id, name, category_id) values(47, 'Other Office Productivity', 5);
insert into public.sub_category (id, name, category_id) values(48, 'Personal Transformation', 6);
insert into public.sub_category (id, name, category_id) values(49, 'Personal Productivity', 6);
insert into public.sub_category (id, name, category_id) values(50, 'Leadership', 6);
insert into public.sub_category (id, name, category_id) values(51, 'Carreer Devlopment', 6);
insert into public.sub_category (id, name, category_id) values(52, 'Parenting & Relationships', 6);
insert into public.sub_category (id, name, category_id) values(53, 'Happiness', 6);
insert into public.sub_category (id, name, category_id) values(54, 'Esoteric Practices', 6);
insert into public.sub_category (id, name, category_id) values(55, 'Religion & Spirituality', 6);
insert into public.sub_category (id, name, category_id) values(56, 'Personal Brand Building', 6);
insert into public.sub_category (id, name, category_id) values(57, 'Creativity', 6);
insert into public.sub_category (id, name, category_id) values(58, 'Influence', 6);
insert into public.sub_category (id, name, category_id) values(59, 'Self Esteem & Confidence', 6);
insert into public.sub_category (id, name, category_id) values(60, 'Stress Management', 6);
insert into public.sub_category (id, name, category_id) values(61, 'Memory & Study Skills', 6);
insert into public.sub_category (id, name, category_id) values(62, 'Motivation', 6);
insert into public.sub_category (id, name, category_id) values(63, 'Other Personal Devlopment', 6);
insert into public.sub_category (id, name, category_id) values(64, 'Web Design', 7);
insert into public.sub_category (id, name, category_id) values(65, 'Graphic Design & Illustration', 7);
insert into public.sub_category (id, name, category_id) values(66, 'Design Tools', 7);
insert into public.sub_category (id, name, category_id) values(67, 'User Experience Design', 7);
insert into public.sub_category (id, name, category_id) values(68, 'Game Design', 7);
insert into public.sub_category (id, name, category_id) values(69, '3D & Animation', 7);
insert into public.sub_category (id, name, category_id) values(70, 'Fashion Design', 7);
insert into public.sub_category (id, name, category_id) values(71, 'Architectural Design', 7);
insert into public.sub_category (id, name, category_id) values(72, 'Interior Design', 7);
insert into public.sub_category (id, name, category_id) values(73, 'Other Design', 7);
insert into public.sub_category (id, name, category_id) values(74, 'Digital Marketing', 8);
insert into public.sub_category (id, name, category_id) values(75, 'Search Engine Optimization', 8);
insert into public.sub_category (id, name, category_id) values(76, 'Social Media Marketing', 8);
insert into public.sub_category (id, name, category_id) values(77, 'Branding', 8);
insert into public.sub_category (id, name, category_id) values(78, 'Marketing Fundamentals', 8);
insert into public.sub_category (id, name, category_id) values(79, 'Marketing Analytics & Automation', 8);
insert into public.sub_category (id, name, category_id) values(80, 'Public Relations', 8);
insert into public.sub_category (id, name, category_id) values(81, 'Paid Advertising', 8);
insert into public.sub_category (id, name, category_id) values(82, 'Video & Mobile Marketing', 8);
insert into public.sub_category (id, name, category_id) values(83, 'Content Marketing', 8);
insert into public.sub_category (id, name, category_id) values(84, 'Growth Hacking', 8);
insert into public.sub_category (id, name, category_id) values(85, 'Affiliate Marketing', 8);
insert into public.sub_category (id, name, category_id) values(86, 'Product Marketing', 8);
insert into public.sub_category (id, name, category_id) values(87, 'Other Marketing', 8);
insert into public.sub_category (id, name, category_id) values(88, 'Arts & Crafts', 9);
insert into public.sub_category (id, name, category_id) values(89, 'Beauty & Makeup', 9);
insert into public.sub_category (id, name, category_id) values(90, 'Esoteric Practices', 9);
insert into public.sub_category (id, name, category_id) values(91, 'Food & Beverage', 9);
insert into public.sub_category (id, name, category_id) values(92, 'Gaming', 9);
insert into public.sub_category (id, name, category_id) values(93, 'Home Improvement & Gardening', 9);
insert into public.sub_category (id, name, category_id) values(94, 'Pet Care & Training', 9);
insert into public.sub_category (id, name, category_id) values(95, 'Travel', 9);
insert into public.sub_category (id, name, category_id) values(96, 'Other Lifestyle', 9);
insert into public.sub_category (id, name, category_id) values(97, 'Digital Photography', 10);
insert into public.sub_category (id, name, category_id) values(98, 'Photography', 10);
insert into public.sub_category (id, name, category_id) values(99, 'Portrait Photography', 10);
insert into public.sub_category (id, name, category_id) values(100, 'Photography Tools', 10);
insert into public.sub_category (id, name, category_id) values(101, 'Commercial Photography', 10);
insert into public.sub_category (id, name, category_id) values(102, 'Video Design', 10);
insert into public.sub_category (id, name, category_id) values(103, 'Other Photography & Video', 10);
insert into public.sub_category (id, name, category_id) values(104, 'Fitness', 11);
insert into public.sub_category (id, name, category_id) values(105, 'General Health', 11);
insert into public.sub_category (id, name, category_id) values(106, 'Sports', 11);
insert into public.sub_category (id, name, category_id) values(107, 'Nutrition & Diet', 11);
insert into public.sub_category (id, name, category_id) values(108, 'Yoga', 11);
insert into public.sub_category (id, name, category_id) values(109, 'Mental Health', 11);
insert into public.sub_category (id, name, category_id) values(110, 'Martial Arts & Self Defense', 11);
insert into public.sub_category (id, name, category_id) values(111, 'Safety & First Aid', 11);
insert into public.sub_category (id, name, category_id) values(112, 'Dance', 11);
insert into public.sub_category (id, name, category_id) values(113, 'Meditation', 11);
insert into public.sub_category (id, name, category_id) values(114, 'Other Health & Fitness', 11);
insert into public.sub_category (id, name, category_id) values(115, 'Instruments', 12);
insert into public.sub_category (id, name, category_id) values(116, 'Music Production', 12);
insert into public.sub_category (id, name, category_id) values(117, 'Music Fundamentals', 12);
insert into public.sub_category (id, name, category_id) values(118, 'Vocal', 12);
insert into public.sub_category (id, name, category_id) values(119, 'Music Techniques', 12);
insert into public.sub_category (id, name, category_id) values(120, 'Music Software', 12);
insert into public.sub_category (id, name, category_id) values(121, 'Other Music', 12);
insert into public.sub_category (id, name, category_id) values(122, 'Engineering', 13);
insert into public.sub_category (id, name, category_id) values(123, 'Humanities', 13);
insert into public.sub_category (id, name, category_id) values(124, 'Math', 13);
insert into public.sub_category (id, name, category_id) values(125, 'Science', 13);
insert into public.sub_category (id, name, category_id) values(126, 'Online Eduacation', 13);
insert into public.sub_category (id, name, category_id) values(127, 'Social Science', 13);
insert into public.sub_category (id, name, category_id) values(128, 'Language Learning', 13);
insert into public.sub_category (id, name, category_id) values(129, 'Teacher Training', 13);
insert into public.sub_category (id, name, category_id) values(130, 'Test Prep', 13);
insert into public.sub_category (id, name, category_id) values(131, 'Other Teaching & Academics', 13);